apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  labels:
    app: py-app
spec:
  replicas: 10
  selector:
    matchLabels:
    # this has to match metadata labels app in this manifest currently line 20
      app: py-app
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: pyapp-container
        image: nwalker494/pyapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
# this is just the name of the service
  name: pyapp-service
spec:
  type: LoadBalancer
  selector:
  # this has to be the name of which to tie into on linemetadata labels app in the manifest currently line 6
    app: py-app
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8080