apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: python-app
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: pythonapp-container
        image: nwalker494/pythonapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
spec:
  type: ClusterIP
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 8080