apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxpy
  namespace: {{ns}}
  labels:
    app: nginxpy
    # type: front end / back end etc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxpy
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginxpy
    spec:
      containers:
      - name: nginxpy-container
        image: eu.gcr.io/lbg-cloud-incubation/nginxpy-custom:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxpy-service
  namespace: {{ns}}
spec:
  type: LoadBalancer
  selector:
    app: nginxpy
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
